allInOne:
  enabled: false

collector:
  enabled: true
  image:
    tag: latest
  service:
    type: ClusterIP
    # Define the main collector ports
    grpc:
      port: 14250
    http:
      port: 14268
    # OTLP ports configuration
    otlp:
      grpc:
        name: otlp-grpc
        port: 4317
      http:
        name: otlp-http
        port: 4318

  extraEnv:
    - name: COLLECTOR_OTLP_ENABLED
      value: "true"
    - name: SPAN_STORAGE_TYPE
      value: memory

storage:
  type: memory
  options:
    memory:
      max-traces: 100000

query:
  enabled: true
  image:
    tag: latest
  service:
    type: ClusterIP
    port: 16686

agent:
  enabled: false

hotrod:
  enabled: true
  args:
    - all
  extraArgs:
    - --otel-exporter=otlp
  extraEnv:
    - name: OTEL_EXPORTER_OTLP_ENDPOINT
      value: http://jaeger-test-collector.observability.svc.cluster.local:4318
    - name: OTEL_EXPORTER_OTLP_PROTOCOL
      value: http/protobuf
    - name: OTEL_SERVICE_NAME
      value: hotrod
    - name: OTEL_LOG_LEVEL
      value: debug