mode: deployment

image:
  repository: otel/opentelemetry-collector
  tag: latest

config:
  receivers:
    otlp:
      protocols:
        http:
          endpoint: 0.0.0.0:4318
        grpc: {}
  processors:
    batch: {}
  exporters:
    otlp:
      endpoint: "jaeger-test-collector.observability.svc.cluster.local:4317"
      tls:
        insecure: true
  service:
    pipelines:
      traces:
        receivers: [otlp]
        processors: [batch]
        exporters: [otlp]
