apiVersion: v1
kind: Service
metadata:
  name: jaeger
spec:
  selector:
    app: example-hotrod
  type: NodePort
  ports:
    - name: jaeger-ui
      protocol: TCP
      port: 16686
      targetPort: 16686
      nodePort: 31670 # Choose an available port between 30000-32767
    - name: otlp-http
      protocol: TCP
      port: 4318
      targetPort: 4318
      nodePort: 30418
    - name: otlp-grpc
      protocol: TCP
      port: 4317
      targetPort: 4317
      nodePort: 30417
