apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotrod
  namespace: example-hotrod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hotrod
  template:
    metadata:
      labels:
        app: hotrod
    spec:
      containers:
        - name: hotrod
          image: jaegertracing/example-hotrod:latest
          args: ["all"]
          env:
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://jaeger:4318
            - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
              value: http://jaeger:4318/v1/traces
---
apiVersion: v1
kind: Service
metadata:
  name: hotrod
  namespace: example-hotrod
spec:
  selector:
    app: hotrod
  ports:
    - name: http
      port: 8080
      targetPort: 8080
