apiVersion: v1
kind: Service
metadata:
  name: jaeger-hotrod
spec:
  selector:
    app: hotrod
  ports:
    - name: hotrod
      port: 8080
      targetPort: 8080
      nodePort: 31687
  type: NodePort
