apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: example-hotrod
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    scrape_configs:
      - job_name: aggregated-trace-metrics
        static_configs:
          - targets: ['otel-collector:8889']
