apiVersion: v1
kind: Service
metadata:
  name: otel-collector
  namespace: example-hotrod
spec:
  selector:
    app: otel-collector
  ports:
    - name: metrics
      port: 8889
      targetPort: metrics
      protocol: TCP
